# Generated by Django 3.0 on 2019-12-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('whatyouhavedone', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=200)),
                ('Certification', models.BooleanField(default=False)),
            ],
        ),
    ]
